### ISSUE TITLE
bbb.io Bullseye + 5.10.x-ti + gcc-pvr 12 + TI PRU 6.0 package

### ISSUE THREAD

**Issue by RobertCNelson** [VedantParanjape/simpPRU#25]
I'll have a base image ready tomorrow, with binutils-pru and gcc-pru pre-installed..

Ti's support package is located here:
```
/usr/lib/ti/pru-software-support-package-v6.0/
```

I wonder, do i need a build flag for that directory..
```
dh build
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   dh_update_autotools_config
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/<<PKGBUILDDIR>>'
git clone https://github.com/VedantParanjape/simpPRU --depth=1
Cloning into 'simpPRU'...
mkdir -p ./simpPRU/build ; cd ./simpPRU/build ; cmake .. ; make ; make install
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found BISON: /usr/bin/bison (found version "3.7.5") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
git found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation
-- Configuring done
-- Generating done
-- Build files have been written to: /<<PKGBUILDDIR>>/simpPRU/build
make[2]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[3]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[4]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
[  2%] [FLEX][lexer] Building scanner with flex 2.6.4
[  2%] [BISON][parser] Building parser with bison 3.7.5
Scanning dependencies of target simppru-1.4
make[4]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[4]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
[  2%] Building C object CMakeFiles/simppru-1.4.dir/src/ast.c.o
[  4%] Building C object CMakeFiles/simppru-1.4.dir/src/code_printer.c.o
[  6%] Building C object CMakeFiles/simppru-1.4.dir/src/firmware_loader.c.o
[  6%] Building C object CMakeFiles/simppru-1.4.dir/src/main.c.o
[  8%] Building C object CMakeFiles/simppru-1.4.dir/src/pin_config.c.o
[ 10%] Building C object CMakeFiles/simppru-1.4.dir/src/semantic.c.o
[ 10%] Building C object CMakeFiles/simppru-1.4.dir/src/symbol_table.c.o
[ 13%] Building C object CMakeFiles/simppru-1.4.dir/third-party/cJSON/cJSON.c.o
[ 15%] Building C object CMakeFiles/simppru-1.4.dir/third-party/vec/vec.c.o
[ 15%] Building C object CMakeFiles/simppru-1.4.dir/src/parser.c.o
[ 17%] Building C object CMakeFiles/simppru-1.4.dir/src/lexer.c.o
[ 19%] Linking C executable ../bin/simppru-1.4
make[4]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
[ 19%] Built target simppru-1.4
make[4]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
Scanning dependencies of target prurpmsg1-1.4
make[4]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[4]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
[ 19%] Building C object src/pru/CMakeFiles/prurpmsg1-1.4.dir/pru_rpmsg.c.o
pru-gcc: fatal error: cannot read spec file ‘device-specs/am335x.pru1’: No such file or directory
compilation terminated.
make[4]: *** [src/pru/CMakeFiles/prurpmsg1-1.4.dir/build.make:82: src/pru/CMakeFiles/prurpmsg1-1.4.dir/pru_rpmsg.c.o] Error 1
make[4]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[3]: *** [CMakeFiles/Makefile2:367: src/pru/CMakeFiles/prurpmsg1-1.4.dir/all] Error 2
make[3]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[2]: *** [Makefile:171: all] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[2]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[3]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[4]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[4]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
[ 19%] Built target simppru-1.4
make[4]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[4]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[4]: Entering directory '/<<PKGBUILDDIR>>/simpPRU/build'
[ 19%] Building C object src/pru/CMakeFiles/prurpmsg1-1.4.dir/pru_rpmsg.c.o
pru-gcc: fatal error: cannot read spec file ‘device-specs/am335x.pru1’: No such file or directory
compilation terminated.
make[4]: *** [src/pru/CMakeFiles/prurpmsg1-1.4.dir/build.make:82: src/pru/CMakeFiles/prurpmsg1-1.4.dir/pru_rpmsg.c.o] Error 1
make[4]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[3]: *** [CMakeFiles/Makefile2:367: src/pru/CMakeFiles/prurpmsg1-1.4.dir/all] Error 2
make[3]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[2]: *** [Makefile:171: all] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/simpPRU/build'
make[1]: *** [debian/rules:12: override_dh_auto_configure] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:15: build] Error 2
```

**Comment by VedantParanjape** [comment]
@RobertCNelson afaik, pru-gcc ships their own device spec files, in the gnuprumcu package. Here: https://github.com/dinuxbg/gnuprumcu

Did you bump that as well ?

**Comment by RobertCNelson** [comment]
@VedantParanjape yeap brand new stack!

**Comment by VedantParanjape** [comment]
> @VedantParanjape yeap brand new stack! Binutls gcc and gnuprumcu

I'll try this on my BB setup in the evening. But meanwhile can you run the prugcc examples with the new stack ?

**Comment by RobertCNelson** [comment]
I'll have a fresh image ready in about 12 hours. With all the base applications.. today image didn't have gcc-pru

**Comment by dinuxbg** [comment]
@VedantParanjape , you need to also install `gnuprumcu` .

**Comment by dinuxbg** [comment]
@VedantParanjape , if you rely on RPMSG, you also need to update the PRU firmware. For kernel 5.10 please check the recent commits in:

- https://github.com/dinuxbg/pru-software-support-package , master branch, lab05 for am335x
- https://github.com/dinuxbg/pru-gcc-examples , master branch, example hc-sr04-range-sensor

**Comment by VedantParanjape** [comment]
> @VedantParanjape , if you rely on RPMSG, you also need to update the PRU firmware. For kernel 5.10 please check the recent commits in:
> 
>     * https://github.com/dinuxbg/pru-software-support-package , master branch, lab05 for am335x
> 
>     * https://github.com/dinuxbg/pru-gcc-examples , master branch, example hc-sr04-range-sensor

Hi @dinuxbg I took a look, but couldn't figure out the issue. Can you please give a gist of the changes needed ?

**Comment by VedantParanjape** [comment]
@RobertCNelson https://github.com/dinuxbg/pru-software-support-package/commit/8c961a4def32cb0194325d033c5621a717882b85 seeing this commit message, it seems that upgrading simppru to support 5.10 will break compatibility with the older versions. It'll take time to port it to 5.10 ig

**Comment by RobertCNelson** [comment]
Okay, fresh image is up!

So this uses, v5.10.x-ti where ti in their PRU software stack broke everything earlier... On the bight side it's 95% mainline, so this should be the last time we ever re-port things..  I know we still have v4.19.x-ti users, so it would be best to support old and new versions if we could with a build flag..

Here is direct link:

https://rcn-ee.net/rootfs/bb.org/testing/2021-12-29/bullseye-iot/

I'm planning to update these once a month at this location..

https://forum.beagleboard.org/t/debian-11-x-bullseye-monthly-snapshots/31280

Regards,

**Comment by dinuxbg** [comment]
@VedantParanjape , to get the changes made for kernel 5.10:
```
$ git clone https://github.com/dinuxbg/pru-gcc-examples
$ git log origin/linux-4.19-rproc..origin/master
```

The only required change is this: https://github.com/dinuxbg/pru-gcc-examples/commit/e855710536740b5ef50bdfdcb5d5d4c52cff4367 .

**Comment by VedantParanjape** [comment]
> Okay, fresh image is up!
> 
> So this uses, v5.10.x-ti where ti in their PRU software stack broke everything earlier... On the bight side it's 95% mainline, so this should be the last time we ever re-port things.. I know we still have v4.19.x-ti users, so it would be best to support old and new versions if we could with a build flag..
> 
> Here is direct link:
> 
> https://rcn-ee.net/rootfs/bb.org/testing/2021-12-29/bullseye-iot/
> 
> I'm planning to update these once a month at this location..
> 
> https://forum.beagleboard.org/t/debian-11-x-bullseye-monthly-snapshots/31280
> 
> Regards,

Thanks for the Link, any ETA for the LTS release of bullseye ?

**Comment by VedantParanjape** [comment]
> git log origin/linux-4.19-rproc..origin/master

That's brief, thanks :)

**Comment by VedantParanjape** [comment]
@RobertCNelson https://github.com/rcn-ee/repos/pull/55 This PR by @dinuxbg seems to solve this issue. Please feel free to close this issue if it does. I'll create a new issue to track the simpPRU port to 5.10.x-ti kernel

**Comment by RobertCNelson** [comment]
Thanks @VedantParanjape 

all queue'ed up, so bb-simppru will be pre-installed after today..

https://github.com/beagleboard/image-builder/commit/9ae0f974110430f77ce4153d43218be8827dfe9f

Regards,
