### ISSUE TITLE
LED on P9_30 now blinking, but slowly

### ISSUE THREAD

**Issue by MarkAYoder** [VedantParanjape/simpPRU#3]
I'm running led_blink.sim example, except I'm changed it to write to 2, which it says is **P9_30**.  But **P9_30** isn't blinking.

Here's the command:

`simppru --device=bbb --load --pru=0 led_blink.sim `

Checking around:
bone$ **cd /dev/remoteproc/pruss-core0**
bone$ **cat state**
offline
bone$ **echo start > state**
bone$ **cat state** 
running

But still no blink.

bone$ **ls -ls /lib/firmware/am335x-pru0-fw** 
4 -rw-rw-r-- 1 root remoteproc 3756 Aug  3 14:25 /lib/firmware/am335x-pru0-fw

Looks like the right time stamp.

What am I missing?

**Comment by MarkAYoder** [comment]
Well...  it is blinking, but....  With no delay it's on for 7 seconds, then off for 7 seconds.

What delay should I expect?

**Comment by VedantParanjape** [comment]
Hey, --load, doesnot support BBB as of now. I didn't have a BBB around, so i had a bit of issue.

If you have beaglebone black(not the wireless one). Will you please post the output of the following command:

`cat /proc/device-tree/model`

**Comment by VedantParanjape** [comment]
> I'm running led_blink.sim example, except I'm changed it to write to 2, which it says is **P9_30**. But **P9_30** isn't blinking.
> 
> Here's the command:
> 
> `simppru --device=bbb --load --pru=0 led_blink.sim `
> 
> Checking around:
> bone$ **cd /dev/remoteproc/pruss-core0**
> bone$ **cat state**
> offline
> bone$ **echo start > state**
> bone$ **cat state**
> running
> 
> But still no blink.
> 
> bone$ **ls -ls /lib/firmware/am335x-pru0-fw**
> 4 -rw-rw-r-- 1 root remoteproc 3756 Aug 3 14:25 /lib/firmware/am335x-pru0-fw
> 
> Looks like the right time stamp.
> 
> What am I missing?

You can pass P9_30 to digital_write too, like this

```
while : 1 == 1 {
    digital_write(P9_30, true);
    delay(1000);
    digital_write(P9_30, false);
    delay(1000);
}
```

**Comment by VedantParanjape** [comment]
> Well... it is blinking, but.... With no delay it's on for 7 seconds, then off for 7 seconds.
> 
> What delay should I expect?

You should expect a 1 second delay. Are you sure you are using the non-wireless BBB ?

**Comment by MarkAYoder** [comment]
I'm running a Black.

bone$ **cat /proc/device-tree/model** 
TI AM335x BeagleBone Black

I currently can't run it on my Pocket since the PRUs aren't starting correctly.

**Comment by VedantParanjape** [comment]
Fixed in ad4048a.

Please pull, and retry, and let me know if this fixes the bug.

Thanks and Regards,
Vedant Paranjape

**Comment by MarkAYoder** [comment]
Wow, that's much faster now.  I'm measuring 1.3WHz with 0 delay.
What made it so much faster?

**Comment by VedantParanjape** [comment]
> Wow, that's much faster now. I'm measuring 1.3WHz with 0 delay.
> What made it so much faster?

What is WHz ? I think, the program was never loaded in PRU, that is why delay was so large.

> I'm measuring 1.3WHz with 0 delay.

Do you mean like this `delay(0)` by with 0 delay.

**Comment by MarkAYoder** [comment]
Well, if I could type.  That should be 1.3MHz.  

Yes, delay(0).

p.s.  I have c code that toggles at 50MHz.

**Comment by VedantParanjape** [comment]
This how i have defined the code printer for delay: https://github.com/VedantParanjape/simpPRU/blob/ad3d0fb804aa7a0b3585906a36b73e6be75f5348/src/code_printer.c#L345

Anything seems wrong ? i simply used the __delay_cycles function provided by GCC-PRU
