### ISSUE TITLE
Is there no support for the blue?

### ISSUE THREAD

**Issue by dmalawey** [VedantParanjape/simpPRU#4]
According to this page it says bbb is supported.  Does that mean black is included and not Blue?

https://simppru.readthedocs.io/en/latest/

**Comment by VedantParanjape** [comment]
I don't have a blue with me, bbb stands for beaglebone black.

Does it have same pin mux as black, if yes, It is a 2 min job.

**Comment by dmalawey** [comment]
I really don't know.  Here's what's produced when I cat:

debian@beaglebone:/var/lib/cloud9$ cat /proc/device-tree/model
TI AM335x BeagleBone Bluedebian@beaglebone:/var/lib/cloud9$

**Comment by VedantParanjape** [comment]
Can you upload the output on something like paste bin?

You can use it to generate binary on any machine, so yes you can generate binary, but the auto pin muxing stuff won't work.

**Comment by dmalawey** [comment]
I am a bit confused. only got one line... am I supposed to have more than this?

`TI AM335x BeagleBone`

**Comment by VedantParanjape** [comment]
I think it should be

` TI AM335x BeagleBone Blue`

**Comment by dmalawey** [comment]
What country are you in?  I can ask my university's department to send you one.  They might, since they are actively using this device in labs.

**Comment by VedantParanjape** [comment]
I'm in India

**Comment by dmalawey** [comment]
That may be tricky.  I'll see if I can get help with beagle.org first before trying to send parts out.   Do you prefer that I close this issue for now?

**Comment by VedantParanjape** [comment]
Actually, this is a gsoc project with beagleboard, I was sent BBBW, BBAI
 and Pocketbeagle for testing by them.

You can keep the issue open, not a problem.

From where will you ship? USA?

**Comment by VedantParanjape** [comment]
Shipping into india will be costly, and take a lot of time. You could rather order to my address from Indian stores like these: https://www.robocraze.com/beaglebone-blue?sa=X&ved=0ahUKEwi0xsD69e_rAhXczjgGHQJPDvYQgOUECKUG

**Comment by VedantParanjape** [comment]
@dmalawey I have mailed you, any updates

**Comment by dmalawey** [comment]
As an individual I do not have funding for this.  In the last few years I worked at a university where they are using the Blue in lab.  I will pass this on to them.  There's a chance that this will be beneficial enough for the lab that they would send you a blue to get this help.  Please standby.

**Comment by VedantParanjape** [comment]
Sure, I will :)

**Comment by VedantParanjape** [comment]
@dmalawey Wanted to give a update, jason shipped a blue to me, will receive it in about 3 weeks.

**Comment by VedantParanjape** [comment]
@dmalawey #22 Added support for Blue
