### ISSUE TITLE
Links in the docs are not working

### ISSUE THREAD

**Issue by SAtacker** [VedantParanjape/simpPRU#5]
The [Installation](https://simppru.readthedocs.io/install/install) link seems to be lost (404)

```
Installation

For Instructions head over to Installation
```

Same Issue with 
- [Detailed Usage](https://simppru.readthedocs.io/usage/usage-simppru)
- [Build](https://simppru.readthedocs.io/install/build)

```
For detailed usage head to Detailed Usage
```

```
Build from source

For Instructions head over to Building from source
```

However on adding /en/latest/ to https://simppru.readthedocs.io/ i.e. before usage/usage-simppru seems to work for all

**Comment by VedantParanjape** [comment]
Solved by #7
